name: テストとバージョン公開

on:
  push:
    branches:
      - main

jobs:
  test-packages:
    name: テスト：ライブラリ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"
      - name: 依存ライブラリのインストール
        run: pnpm i
      - name: テスト実行
        run: pnpm test

  # https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
  test-vscode:
    name: テスト：VSCode
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"
      - name: 依存ライブラリのインストール
        run: pnpm i
      - name: テスト実行(Linux)
        run: xvfb-run -a pnpm test-vscode
        if: runner.os == 'Linux'
      - name: テスト実行(Linux以外)
        run: pnpm test-vscode
        if: runner.os != 'Linux'

  release:
    name: バージョン公開
    runs-on: ubuntu-latest
    needs: [test-packages, test-vscode]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"
      - name: 依存ライブラリのインストール
        run: pnpm i
      - name: パッケージのビルド
        run: pnpm build
      - name: リリースPR作成 or npmに公開
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm -r publish
          version: pnpm new-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: blogview-vscodeのリリース
        run: |
          cd packages/blogview-vscode
          PUBLISHED=$(pnpm vsce search blogview-vscode --json | jq -r '.[].versions[0].version')
          CURRENT=$(cat package.json | jq -r '.version')
          if [ "$PUBLISHED" != "$CURRENT" ]; then
            pnpm release -- -p "$VSCE_TOKEN"
          fi
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
